let API='http://127.0.0.1:8000';let token=localStorage.getItem('ai_api_token')||'';let selected=null;
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function headers(json=true){const h={};if(json)h['Content-Type']='application/json';if(token)h.Authorization='Bearer '+token;return h}
async function init(){try{API=(await window.aiSystem.getConfig()).apiBase||API}catch{};await loadStatus();await loadArtifacts();}
function add(role,text){const d=document.createElement('div');d.className='msg '+(role==='user'?'user':'ai');d.innerHTML='<small>'+esc(role==='user'?'YOU':'JARVIS')+'</small>'+esc(text);$('messages').appendChild(d);$('messages').scrollTop=$('messages').scrollHeight}
async function send(text){text=(text||$('input').value).trim();if(!text)return;$('input').value='';add('user',text);setMood('thinking');try{const r=await fetch(API+'/v1/agent/chat',{method:'POST',headers:headers(),body:JSON.stringify({model:'auto',assistant_profile:'general',messages:[{role:'user',content:text}],stream:false,max_tool_rounds:8})});const j=await r.json();if(j.confirmation){add('ai','Confirmation required: '+(j.confirmation.reason||'This action needs approval.'));setMood('idle');return}add('ai',j.message?.content||j.detail||JSON.stringify(j));await loadArtifacts()}catch(e){add('ai','Connection error: '+e.message);setMood('error');return}setMood('idle')}
function setMood(m){$('face').className='face '+m;$('faceStatus').textContent=m.toUpperCase()}
async function loadArtifacts(){try{const j=await (await fetch(API+'/v1/artifacts',{headers:headers(false)})).json();const items=j.items||[];$('artifactCount').textContent=items.length;$('artifactList').innerHTML=items.slice(0,8).map(a=>`<div class="artifact-item" data-id="${esc(a.id)}"><b>${esc(a.title)}</b><small>${esc(a.kind)}</small></div>`).join('')||'<div style="padding:12px;color:#7d89a6;font-size:9px">No artifacts yet.</div>';document.querySelectorAll('.artifact-item').forEach(x=>x.onclick=()=>selectArtifact(x.dataset.id));}catch{$('artifactList').innerHTML='<div style="padding:12px;color:#7d89a6;font-size:9px">Artifacts unavailable.</div>'}}
async function selectArtifact(id){try{const a=await (await fetch(API+'/v1/artifacts/'+encodeURIComponent(id),{headers:headers(false)})).json();selected=a;$('artifactTitle').textContent=a.title||'Artifact';let body=a.content||'';if(a.kind==='image'&&(body.startsWith('http')||body.startsWith('data:')||body.startsWith('file:'))) $('artifactBody').innerHTML='<img class="artifact-image" src="'+esc(body)+'" alt="'+esc(a.title)+'">';else $('artifactBody').innerHTML='<div class="artifact-content">'+esc(body)+'</div>'}catch{}}
async function loadStatus(){try{const j=await (await fetch(API+'/v1/system/status',{headers:headers(false)})).json();$('apiStatus').textContent='Gateway online';$('ollama').textContent=j.ollama?.status||'unknown';$('host').textContent=j.host_bridge?.status||'unknown';$('systemText').textContent='online';const c=await (await fetch(API+'/v1/connections',{headers:headers(false)})).json();const comp=(c.items||[]).find(x=>x.id==='host_bridge');$('computer').textContent=comp?.status||'not configured'}catch{$('apiStatus').textContent='Gateway offline';$('apiDot').style.background='#ff6584';$('systemText').textContent='offline'}}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');const v=b.dataset.view;if(v==='voice')location.href=API+'/voice';if(v==='dashboard')location.href=API+'/dashboard';if(v==='artifacts')loadArtifacts();if(v==='connections')loadStatus();if(v==='computer')add('ai','Computer mode is opt-in. Enable AI_COMPUTER_CONTROL=true on the authenticated host bridge before using it.')});$('send').onclick=()=>send();$('input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$('refreshArtifacts').onclick=loadArtifacts;$('voiceBtn').onclick=()=>location.href=API+'/voice';document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>send(b.dataset.q));$('compactBtn').onclick=()=>document.body.classList.toggle('compact');init();
